FROM mcr.microsoft.com/playwright:v1.50.0-noble  
WORKDIR /app

COPY package*.json ./ 

RUN npm install

COPY . .

# Install Playwright browsers (if not already included in the base image)
RUN npx playwright install --with-deps

# Set the entry point to run the Playwright tests
ENTRYPOINT ["npx", "playwright", "test"]
