version: '3.8'

services:
  webapp:
    image: busapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"