// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicketReservationApp.Data;

#nullable disable

namespace TicketReservationApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "57c64f2b-0ada-4b64-9bc9-ab1e260a276a",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "d8533f12-c1f9-42bf-bbad-67e282555214",
                            RoleId = "57c64f2b-0ada-4b64-9bc9-ab1e260a276a"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TicketReservationApp.Models.Posts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = "d8533f12-c1f9-42bf-bbad-67e282555214",
                            PostContent = "seed 1",
                            PostTitle = "first post",
                            PostType = "info"
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = "d8533f12-c1f9-42bf-bbad-67e282555214",
                            PostContent = "seed 2",
                            PostTitle = "second post",
                            PostType = "warning"
                        },
                        new
                        {
                            Id = 3,
                            AppUserId = "d8533f12-c1f9-42bf-bbad-67e282555214",
                            PostContent = "seed 3",
                            PostTitle = "third post",
                            PostType = "info"
                        });
                });

            modelBuilder.Entity("TicketReservationApp.Models.Tickets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Departure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("Expired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seat")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimetablesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("TimetablesId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = "d8533f12-c1f9-42bf-bbad-67e282555214",
                            Date = new DateTime(2024, 9, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            Departure = "Joensuu",
                            Destination = "Tampere",
                            EndTime = new TimeSpan(0, 9, 0, 0, 0),
                            Expired = false,
                            Name = "arttu",
                            Seat = 12,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Status = "paid",
                            TimetablesId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = "d8533f12-c1f9-42bf-bbad-67e282555214",
                            Date = new DateTime(2024, 9, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            Departure = "Joensuu",
                            Destination = "Tampere",
                            EndTime = new TimeSpan(0, 9, 0, 0, 0),
                            Expired = false,
                            Name = "juhani",
                            Seat = 13,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Status = "paid",
                            TimetablesId = 1
                        },
                        new
                        {
                            Id = 3,
                            AppUserId = "d8533f12-c1f9-42bf-bbad-67e282555214",
                            Date = new DateTime(2024, 9, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Departure = "Joensuu",
                            Destination = "Tampere",
                            EndTime = new TimeSpan(0, 9, 0, 0, 0),
                            Expired = false,
                            Name = "name",
                            Seat = 5,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Status = "paid",
                            TimetablesId = 1
                        },
                        new
                        {
                            Id = 4,
                            AppUserId = "d8533f12-c1f9-42bf-bbad-67e282555214",
                            Date = new DateTime(2024, 9, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            Departure = "Joensuu",
                            Destination = "Kuopio",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            Expired = false,
                            Name = "name",
                            Seat = 10,
                            StartTime = new TimeSpan(0, 17, 0, 0, 0),
                            Status = "paid",
                            TimetablesId = 2
                        },
                        new
                        {
                            Id = 5,
                            AppUserId = "d8533f12-c1f9-42bf-bbad-67e282555214",
                            Date = new DateTime(2024, 9, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            Departure = "Joensuu",
                            Destination = "Kuopio",
                            EndTime = new TimeSpan(0, 9, 0, 0, 0),
                            Expired = false,
                            Name = "name",
                            Seat = 9,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Status = "paid",
                            TimetablesId = 2
                        },
                        new
                        {
                            Id = 6,
                            AppUserId = "d8533f12-c1f9-42bf-bbad-67e282555214",
                            Date = new DateTime(2024, 9, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            Departure = "Joensuu",
                            Destination = "Kuopio",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            Expired = false,
                            Name = "name",
                            Seat = 12,
                            StartTime = new TimeSpan(0, 17, 0, 0, 0),
                            Status = "paid",
                            TimetablesId = 3
                        });
                });

            modelBuilder.Entity("TicketReservationApp.Models.Timetables", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<DateTime>>("Cancelled")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone[]");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<List<string>>("Day")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Departure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double?>("PriceDiscount")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Timetables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = "d8533f12-c1f9-42bf-bbad-67e282555214",
                            Cancelled = new List<DateTime>(),
                            Date = new DateTime(2024, 9, 15, 15, 39, 11, 691, DateTimeKind.Utc).AddTicks(1615),
                            Day = new List<string> { "monday", "tuesday", "wednesday", "thursday", "friday" },
                            Departure = "Joensuu",
                            Destination = "Tampere",
                            EndTime = new TimeSpan(0, 9, 0, 0, 0),
                            Price = 29.989999999999998,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = "d8533f12-c1f9-42bf-bbad-67e282555214",
                            Cancelled = new List<DateTime>(),
                            Date = new DateTime(2024, 9, 15, 15, 39, 11, 691, DateTimeKind.Utc).AddTicks(1674),
                            Day = new List<string> { "saturday", "sunday" },
                            Departure = "Joensuu",
                            Destination = "Kuopio",
                            EndTime = new TimeSpan(0, 9, 0, 0, 0),
                            Price = 19.989999999999998,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            AppUserId = "d8533f12-c1f9-42bf-bbad-67e282555214",
                            Cancelled = new List<DateTime>(),
                            Date = new DateTime(2024, 9, 15, 15, 39, 11, 691, DateTimeKind.Utc).AddTicks(1680),
                            Day = new List<string> { "saturday", "sunday" },
                            Departure = "Joensuu",
                            Destination = "Kuopio",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            Price = 29.989999999999998,
                            StartTime = new TimeSpan(0, 17, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            AppUserId = "d8533f12-c1f9-42bf-bbad-67e282555214",
                            Cancelled = new List<DateTime>(),
                            Date = new DateTime(2024, 9, 15, 15, 39, 11, 691, DateTimeKind.Utc).AddTicks(1687),
                            Day = new List<string> { "monday", "tuesday", "wednesday", "thursday", "friday" },
                            Departure = "Joensuu",
                            Destination = "Nurmes",
                            EndTime = new TimeSpan(0, 9, 0, 0, 0),
                            Price = 14.99,
                            PriceDiscount = 10.99,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("TicketReservationApp.Data.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "d8533f12-c1f9-42bf-bbad-67e282555214",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "356a12e6-3be8-42fd-a8bf-69831005e89a",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEK8W5yttCSIhCflkj0qAF/YD0d0V+6HBqjgqydM3zRK9tzyjp6/KedElVrTwpHDKaQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin@example.com"
                        });
                });

            modelBuilder.Entity("TicketReservationApp.Models.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<int>("PostsId")
                        .HasColumnType("integer");

                    b.Property<int>("TicketsId")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketReservationApp.Models.Posts", b =>
                {
                    b.HasOne("TicketReservationApp.Models.AppUser", "AppUser")
                        .WithMany("Posts")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("TicketReservationApp.Models.Tickets", b =>
                {
                    b.HasOne("TicketReservationApp.Models.AppUser", "AppUser")
                        .WithMany("Tickets")
                        .HasForeignKey("AppUserId");

                    b.HasOne("TicketReservationApp.Models.Timetables", "Timetables")
                        .WithMany("Tickets")
                        .HasForeignKey("TimetablesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Timetables");
                });

            modelBuilder.Entity("TicketReservationApp.Models.Timetables", b =>
                {
                    b.HasOne("TicketReservationApp.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("TicketReservationApp.Models.Timetables", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketReservationApp.Models.AppUser", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
