global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["dev-cadvisor:8080"]
  - job_name: "dotnet"
    static_configs:
      - targets: ["webapp:5001"]
