name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }} # Use your GitHub Secret for the SSH private key

      - name: SSH into VPS and deploy
        run: |
          ssh -o StrictHostKeyChecking=no  -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
          if [ ! -d \"${{ secrets.VPS_PROJECT_PATH }}/.git\" ]; then
            git clone git@github.com:your-username/your-repo.git ${{ secrets.VPS_PROJECT_PATH }};
          else
            cd ${{ secrets.VPS_PROJECT_PATH }} && git pull origin master;
          fi &&
          cd ${{ secrets.VPS_PROJECT_PATH_ENV }} &&
          echo 'DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}' > .env &&
          echo 'SECRET_KEY=${{ secrets.STRIPE_SECRET }}' >> .env &&
          cd ${{ secrets.VPS_PROJECT_PATH }} &&
          sudo docker-compose -f docker-compose.prod.yml down --remove-orphans &&
          sudo docker network prune -f &&  # Prunes unused networks
          sudo docker-compose -f docker-compose.prod.yml up -d --build"  # Use production file
