name: Docker - e2e tests

on:
  pull_request:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo 'DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}' > ./backend/.env &&
          echo 'SECRET_KEY=${{ secrets.STRIPE_SECRET }}' >> ./backend/.env && 
          echo 'EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}' >> ./backend/.env

      - name: Start frontend e2e tests
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.test-e2e.yml"
          up-flags: "--build --remove-orphans"

      - name: Shut down docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.test-e2e.yml"
          down-flags: ""
