name: Run Cypress Tests

on:
  pull_request:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest # GitHub Actions runner

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Create env file
        run: |
          echo 'DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}' > ./backend/.env &&
          echo 'SECRET_KEY=${{ secrets.STRIPE_SECRET }}' >> ./backend/.env && 
          echo 'EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}' >> ./backend/.env &&
          echo 'EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}' >> ./backend/.env &&
          echo 'EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}' >> ./backend/.env &&
          echo 'PROD_DOMAIN=${{ secrets.PROD_DOMAIN }}' >> ./backend/.env &&
          echo 'GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}' >> .env &&
          echo 'GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}' >> .env

      - name: Restore .NET dependencies
        run: |
          cd backend
          dotnet restore

      - name: Build .NET app
        run: |
          cd backend
          dotnet build

      - name: Start backend app
        run: |
          cd backend
          dotnet run --launch-profile "Test" &
          sleep 30
          curl --max-time 60 -f -v http://localhost:5001/api/posts || (echo "Problem with endpoint")

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Use the latest stable Node.js version

      # Step 3: Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # Step 6: Start the Vite app (frontend)
      - name: Start Vite frontend
        working-directory: ./frontend # Instead of 'cd frontend'
        #env:
        #  VITE_BASEURL: http://localhost:5002 # Set environment variable
        run: npm run dev & # Starts Vite in the background

      # Step 7: Wait for the servers to be ready
      #- name: Wait for Vite and backend to start
      #  run: |
      #    npx wait-on http://localhost:5002  # Backend API
      #    npx wait-on http://localhost:5173  # Vite App

      # Step 8: Run Cypress tests
      - name: Run Cypress tests
        run: |
          cd frontend
          npx cypress run --headless
