name: Docker - e2e tests

on:
  pull_request:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo 'DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}' >> ./backend/.env &&
          echo 'SECRET_KEY=${{ secrets.STRIPE_SECRET }}' >> ./backend/.env && 
          echo 'EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}' >> ./backend/.env

      - name: Install Docker Compose # ✅ Fix: Install docker-compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Start backend services
        run: |
          docker-compose -f docker-compose.test-e2e.yml up --build --abort-on-container-exit

      - name: Stop and clean up containers
        run: docker-compose -f docker-compose.test-e2e.yml down
