name: Docker Compose Action

on:
  pull_request:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo 'DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}' > ./backend/.env &&
          echo 'SECRET_KEY=${{ secrets.STRIPE_SECRET }}' >> ./backend/.env && 
          echo 'EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}' >> ./backend/.env

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Start test frontend and backend
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.test.yml"
          up-flags: "test-webapp test-client-vite --build"

      - name: Run Frontend unit tests
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.test.yml"
          up-flags: "test-webapp --build"

      - name: Run Frontend e2e tests
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.test.yml"
          up-flags: "test-client-e2e --build"

      - name: Run Backend tests
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.test.yml"
          up-flags: "test-webapp-run-tests --build"

      - name: Shut down docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.test.yml"
          down-flags: ""
