name: Docker - Unit tests

on:
  pull_request:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start frontend unit tests
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.test-unit.yml"
          up-flags: "--build --remove-orphans --abort-on-container-exit"

      - name: Shut down docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.test-unit.yml"
          down-flags: ""
